# Generated by Django 4.2.1 on 2023-05-09 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('cedula', models.IntegerField(unique=True, verbose_name='Cedula')),
                ('fechaNaci', models.DateField(default=datetime.datetime.now, verbose_name='Fecha Nacimiento')),
                ('fechaRegis', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'ordering': ['id'],
            },
        ),
    ]
