# Generated by Django 4.2.1 on 2023-05-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='categora',
        ),
        migrations.AlterModelTable(
            name='type',
            table='tipo',
        ),
    ]
